var staff = 
{
"city":{ 
	"displayLabel":"City",
	"values":["ALPINE","BOUNTIFUL","DRAPER","FRUIT HEIGHTS","HERRIMAN","HOLLADAY","KAYSVILLE","KEARNS","LEHI","LINDON","MIDVALE","MURRAY","OREM","PARK CITY","PROVO","RIVERTON","S JORDAN","SALEM","SALT LAKE CITY","SANDY","SARATOGA SPRINGS","SO JORDAN","SPANISH FORK","SPRINGVILLE","SYRACUSE","TAYLORSVILLE","TOOELE","WEST JORDAN","WEST VALLEY","WOODS CROSS"
	]
}
}
